In [ ]:
a=[1.0, 2.0, 3.0]

In [8]:
a[0]

1.0

In [10]:
a[2] = 1.0
a

[1.0, 2.0, 1.0]

In [15]:
import torch    #imports the torch module
a = torch.ones(3)   # creates a 1D tensor of size 3 filled with 1s
a

tensor([1., 1., 1.])

In [12]:
a[1]

tensor(1.)

In [13]:
float(a[1])

1.0

In [14]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
""" we are storing coordinates of a triangle (4,1), (5,3) and (2,1)"""
points = torch.zeros(6) #using .zeros is just a way of getting an appropriately sized array
points[0] = 4.0     #overwrite zeros with the values required
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])   #same as above cell
points

tensor([4., 1., 5., 3., 2., 1.])

In [22]:
""" to get coordinates of first point"""
float(points[0]), float(points[1])

(4.0, 1.0)

In [23]:
""" individual 2D coordinates stored in tensor"""
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [24]:
points.shape

torch.Size([3, 2])

In [25]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [26]:
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
points[0,1]

tensor(1.)

In [28]:
points[0]

tensor([4., 1.])

In [29]:
some_list = list(range(6))

In [30]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [ ]:
some_list[1:4]      #[1,4)

[1, 2, 3]

In [32]:
some_list[1:]

[1, 2, 3, 4, 5]

In [33]:
some_list[:4]

[0, 1, 2, 3]

In [34]:
some_list[-1]

5

In [35]:
some_list[1:4:2]

[1, 3]

In [36]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [37]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [39]:
points[1:, 0]

tensor([5., 2.])

In [40]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [41]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [42]:
a, a_t

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [43]:
a = torch.ones(3,2)
a_t = a.transpose(1,0)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [57]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [58]:
print(a)
print(a.storage())
print(a.stride())

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
(2, 1)


/tmp/ipykernel_96452/4006758053.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(a.storage())


In [59]:
a.storage()

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [60]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [62]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])