In [ ]:
a=[1.0, 2.0, 3.0]

In [8]:
a[0]

1.0

In [10]:
a[2] = 1.0
a

[1.0, 2.0, 1.0]

In [15]:
import torch    #imports the torch module
a = torch.ones(3)   # creates a 1D tensor of size 3 filled with 1s
a

tensor([1., 1., 1.])

In [12]:
a[1]

tensor(1.)

In [13]:
float(a[1])

1.0

In [14]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [ ]:
""" we are storing coordinates of a triangle (4,1), (5,3) and (2,1)"""
points = torch.zeros(6) #using .zeros is just a way of getting an appropriately sized array
points[0] = 4.0     #overwrite zeros with the values required
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [ ]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])   #same as above cell
points

tensor([4., 1., 5., 3., 2., 1.])

In [22]:
""" to get coordinates of first point"""
float(points[0]), float(points[1])

(4.0, 1.0)

In [23]:
""" individual 2D coordinates stored in tensor"""
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [24]:
points.shape

torch.Size([3, 2])

In [25]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [26]:
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [27]:
points[0,1]

tensor(1.)

In [28]:
points[0]

tensor([4., 1.])

In [29]:
some_list = list(range(6))

In [30]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [ ]:
some_list[1:4]      #[1,4)

[1, 2, 3]

In [32]:
some_list[1:]

[1, 2, 3, 4, 5]

In [33]:
some_list[:4]

[0, 1, 2, 3]

In [34]:
some_list[-1]

5

In [35]:
some_list[1:4:2]

[1, 3]

In [36]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [37]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [39]:
points[1:, 0]

tensor([5., 2.])

In [40]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [41]:
a = torch.ones(3,2)
a_t = torch.transpose(a,0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [42]:
a, a_t

(tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]))

In [43]:
a = torch.ones(3,2)
a_t = a.transpose(1,0)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [57]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [58]:
print(a)
print(a.storage())
print(a.stride())

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
(2, 1)


/tmp/ipykernel_96452/4006758053.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(a.storage())


In [59]:
a.storage()

 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [60]:
a = torch.ones(3,2)
a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [62]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [63]:
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [64]:
second_point.size()

torch.Size([2])

In [65]:
second_point.shape

torch.Size([2])

In [67]:
points.stride()

(2, 1)

In [68]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [69]:
second_point.storage_offset()

2

In [70]:
second_point.stride()

(1,)

In [71]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0,1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [72]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0,1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [73]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [74]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
id(points.storage()) == id(points_t.storage()) # same storage

True

In [76]:
points.stride()

(2, 1)

In [ ]:
points_t.stride() # differ in shape and stride

(1, 2)

In [80]:
# transposing higher dimenssion
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
some_t.shape

torch.Size([3, 4, 5])

In [81]:
transpose_t.shape

torch.Size([5, 4, 3])

In [82]:
some_t.stride()

(20, 5, 1)

In [83]:
transpose_t.stride()

(1, 5, 20)

In [84]:
points.is_contiguous()

True

In [85]:
points_t.is_contiguous()

False

In [86]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [87]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [90]:
points_t.stride()

(1, 2)

In [91]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [92]:
points_t_cont.stride()

(3, 1)

In [93]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

ImportError: /home/kelvin/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

In [2]:
texts = [
    "I like coffee",
    "I like tea",
    "I like coffee and tea"
]
from collections import Counter

tokens = []
for sentence in texts:
    words = sentence.lower().split()
    tokens.extend(words)

freq = Counter(tokens)
freq


Counter({'i': 3, 'like': 3, 'coffee': 2, 'tea': 2, 'and': 1})

In [1]:
import torch
print("torch:", torch.__version__)
print("cuda:", torch.cuda.is_available())

ImportError: /home/kelvin/miniconda3/envs/torch310/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

In [1]:
import torch
print("torch:", torch.__version__)
print("cuda:", torch.cuda.is_available())
print("python:", __import__("sys").version)

torch: 1.9.1
cuda: False
python: 3.7.13 (default, Mar 29 2022, 02:18:16) 
[GCC 7.5.0]


In [18]:
import string
import numpy as np
import re
from nltk.corpus import stopwords
from collections import Counter
class naive_bayes_classifier():

    def __init__(self, min_freq=1):
         self.min_freq = min_freq
     
    def preprocess_text(self, text):
        text = text.lower()
        translator = str.maketrans('', '', string.punctuation)
        clean_text = text.translate(translator)
        tokens = re.findall(r'\w+', clean_text)
        stop_words = set(stopwords.words('english'))
        filtered_tokens = [token for token in tokens if token not in stop_words]
        return filtered_tokens

    def vocabulary(self, text):
        vocab = {}
        index = 0
        vocab["<UNK>"] = index
        tokens = [] 
        for sentence in text:
            y = self.preprocess_text(sentence)
            tokens.extend(y)
        freq = Counter(tokens)
        for items, counts in freq.items():
            if counts >= self.min_freq:
                index += 1
                vocab[items] = index
        return vocab

    def calculate_class_probabilities(self, labels):
        n = len(labels)
        class_count = {}
        for label in labels:
            if label not in class_count:
                class_count[label] = 0
            class_count[label] += 1
        self.class_priors = {}
        for clas in class_count:
            self.class_priors[clas] = class_count[clas]/n
        return self.class_priors
    
    def calculate_word_probabilities(self, texts, labels, vocab):
        vocab_len = len(vocab)
        classes = set(labels)
        count = {}
        total_word = {}
        prob_cal = {}
        self.word_likelihoods = {}
        for clas in classes:
            total_word[clas] = 0
            count[clas] = np.zeros(vocab_len)
        for text, label in zip(texts, labels):
            tokens = self.preprocess_text(text)
            for token in tokens:
                idx = vocab[token] if token in vocab else vocab["<UNK>"]
                count[label][idx] += 1
                total_word[label] += 1
        for clas in classes:
            prob_cal[clas] = (count[clas] + 1)/(total_word[clas] + vocab_len) 
            temp = {}      
            for word in vocab:
                index = vocab[word]
                prob = prob_cal[clas][index]
                temp[word] = prob
            self.word_likelihoods[clas] = temp
        return self.word_likelihoods

    def fit(self, texts, labels):
        self.vocab = self.vocabulary(texts)
        self.class_priors = self.calculate_class_probabilities(labels)
        self.word_likelihoods = self.calculate_word_probabilities(texts, labels, self.vocab)


    def predict(self, sentence):
        tokens = self.preprocess_text(sentence)
        scores = {}
        for clas in self.class_priors:
            score = np.log(self.class_priors[clas])
            for token in tokens:
                if token not in self.vocab:
                    token = "<UNK>"
                score += np.log(self.word_likelihoods[clas][token])
            scores[clas] = score
        class_with_max_score = max(scores, key=scores.get)
        return class_with_max_score


def main():
    text = ["i love coffee!", "I love tea.", "Do I love any of these? ha ha ha, nice try, but No!", "Sheldon Lee cooper has an iq of 187 but doesn't like coffee.", "he likes tea"]
    labels = [1, 1, 0, 0, 1]
    classifier = naive_bayes_classifier()
    classifier.fit(text, labels)
    print(classifier.predict("kirtiamy"))

if __name__ == "__main__":
    main()

1


In [ ]:
import numpy as np
from collections import Counter
import torch
import torch.nn as nn
import torch.optim as optim
class tfidf_vectorizer():
    def __init__(self, min_freq=2):
        self.min_freq = min_freq
        self.vocab = None
        self.new_list = []
        self.df = None
        self.idf = None
        self.n_docs = None
    
    def vocabulary(self):
        self.texts = [
        "I like coffee",
        "I like tea",
        "I like coffee and tea"
        ]
        tokens = []
        [tokens.extend(sentence.lower().split()) for sentence in self.texts]
        freq = Counter(tokens)
        self.n_docs = len(self.texts)
        # creating vocabulary
        index = 0
        self.vocab = {}
        self.vocab["<UNK>"] = index
        for items, counts in freq.items():
            if counts >= self.min_freq:
                index += 1
                self.vocab[items] = index
    
    def new_sent(self, new_sentence):
        word = new_sentence.lower().split()
        new_list = []
        for w in word:
            if w in self.vocab:
                new_list.append(self.vocab[w])
            else:
                new_list.append(self.vocab["<UNK>"])
        return new_list
    
    def bag_of_words(self, sentence):
        nw = self.new_sent(sentence)
        bow = np.zeros(len(self.vocab))
        for indices in nw:
                bow[indices] += 1
        return bow

    def df_(self):
        self.df = np.zeros(len(self.vocab))
        for sentence in self.texts:
            bow = self.bag_of_words(sentence)
            for i in range(len(bow)):
                if bow[i] > 0:
                    self.df[i] += 1

    def idf_(self):
        self.idf = np.zeros(len(self.vocab))
        for i in range(len(self.df)):
            df__ = self.df[i]
            self.idf[i] = np.log((self.n_docs+1)/(df__+1)) + 1

    def tf_idf(self, sentence):
        bow = self.bag_of_words(sentence)
        tf_idf_ = bow * self.idf
        return tf_idf_
    
    def cosine_similarity(self, sentence1, sentence2):
        x = self.tf_idf(sentence1)
        y = self.tf_idf(sentence2)
        if np.linalg.norm(x) == 0 or np.linalg.norm(y) == 0: 
            return 0
        else:
            cos_sim = np.dot(x, y) / (np.linalg.norm(x) * np.linalg.norm(y))
            return cos_sim

class text_classifier(nn.Module):
    def __init__(self, input_dim, num_classes):
        super().__init__()
        self.linear = nn.Linear(input_dim, num_classes)
    
    def forward(self, x):
        return self.linear(x)
    
def train(model, vectorizer, texts, labels, epochs):
    model.train()
    loss_fn = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(),lr=0.01)
    for epoch in range(epochs):
        total_loss = 0
        for text, label in zip(texts, labels):
            vector = vectorizer.tf_idf(text)
            vector = vector.reshape(1, -1)
            tensor = torch.tensor(vector, dtype=torch.float32)
            output = model(tensor)
            
            label = torch.tensor(label, dtype=torch.long)
            label = label.reshape(1, -1)
            loss = loss_fn(output, label)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            total_loss += loss.item()
        average_loss = total_loss / len(texts)
        print(epoch, average_loss)

def main():
    vectorizer = tfidf_vectorizer()
    vectorizer.vocabulary()
    vectorizer.df_()
    vectorizer.idf_()
    tf_idf_ = vectorizer.tf_idf("I like coffee")
    tf_idf_ = tf_idf_.reshape(1, -1)
    sim = vectorizer.cosine_similarity("I LOVE coffee", "I love milk")
    print(sim)
    model = text_classifier(5, 2)           # nn.Linear(vocab  size, number of classes)
    texts = [
    "I love coffee",
    "I hate coffee",
    "coffee is great",
    "coffee is terrible",
    "I like tea",
    "I dislike tea"
        ]
    labels = [
    1,  # I love coffee
    0,  # I hate coffee
    1,  # coffee is great
    0,  # coffee is terrible
    1,  # I like tea
    0   # I dislike tea
                ] 
    train(model, vectorizer, texts, labels, epochs=5)    

if __name__ == "__main__":
    main()

In [19]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])

# Mean of all elements
print(np.mean(arr)) # 2.5

# Mean along columns (axis 0)
print(np.mean(arr, axis=0)) # [2.0, 3.0]

# Mean with keepdims=True
print(np.mean(arr, axis=0, keepdims=True)) # [[2.0, 3.0]]


2.5
[2. 3.]
[[2. 3.]]


In [2]:
lst = [1, 2, 2, 3]

for x in lst:
    if x == 2:
        lst.remove(x)

print(lst)

[1, 2, 3]


In [3]:
lst = [3, 1, 2]
lst = lst.sort()
print(lst)

None


In [4]:
lst = [5, 2, 4]
new_lst = lst.sort()

print(lst)
print(new_lst)

[2, 4, 5]
None


In [6]:
import cmath
cmath.sqrt(-4)

2j

In [7]:
import cmath
cmath.sqrt(4)

(2+0j)

In [10]:
import math
math.sqrt(4)

2.0

In [11]:
True and False

False

In [13]:
x = 2
y = 3
z = 5
x += 1
print(x)
x -= 4
print(x)
x *= -2.6
print(x)
x /= 5*y
print(x)
x //= 3.4
print(x)
x, y = 2*z+1 , (x+y)/3
print(x, y)

3
-1
2.6
0.17333333333333334
0.0
11 1.0


In [22]:
x = 6
x //= 3
print(x)
x //= 3.0
print(x)
x /= 3.0
print(x)

2
0.0
0.0


In [16]:
print(7/3)
print(7//3)
print(7//3.0)
print(7.0//3)

2.3333333333333335
2
2.0
2.0


In [19]:
print(type(7/3))
print(type(7//3))
print(type(7//3.0))
print(type(7//3.0))

<class 'float'>
<class 'int'>
<class 'float'>
<class 'float'>


In [23]:
x = 7
x = x//3
print(type(x))
print(x)
print(type(7//3))
print(7//3)

<class 'int'>
2
<class 'int'>
2


In [49]:
print(-5/3)
print(-5//3)

-1.6666666666666667
-2


In [36]:
import math
x = -4.5
print(math.ceil(x))
print(math.floor(x))
print(round(x))


-4
-5
-4


In [40]:
x = -4.5789645278964
print(round(x, 3))

-4.579


In [ ]:
x = -4.51
print(round(x))

-4.51


In [44]:
x = 4.500001
print(round(x))

5


In [50]:
print(5%4)
print(-5%4)
print(5%-4)
print(-5%-4)

1
3
-3
-1


In [60]:
print(not 1<2 or 4>2)
print(not(1<2 or 4>2))
print(1<2 or 4>2)
print(4>2 or 10/10==0)
print(not 0<1)
print(1 and 2)
print(1 or 2)
print(0 and 1)
print(1 or 0)
print(type(complex(2,3).real) is not int)

True
False
True
True
False
2
1
0
1
True


In [59]:
print(type(complex(2,3).real))
print(type(complex(2,3).imag))

<class 'float'>
<class 'float'>


In [61]:
print(True + True)
print(10*True)

2
10


In [62]:
print(True is 1)

False


<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
/tmp/ipykernel_123063/1728233177.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(True is 1)


In [63]:
print(True == 1)

True


In [76]:
a = -5
c = -5
print(a == c)
print(a is c)
c = a
print(a == c)
print(a is c)

True
True
True
True


In [68]:
a = [1, 2]
b = 1
c = b
print(a is b)
print(c is b)

False
True


In [74]:
a = [1, 2]
b = 1
c = [1, 2]
print(c is a)
print(c == a)
c = a
print(c is a)


False
True
True


In [85]:
for j in range(1):
    print(j, type(j))

0 <class 'int'>


In [80]:
r = range(3, 5, 3)
print(type(r))
print(r)

<class 'range'>
range(3, 5, 3)


In [84]:
for j in range(3,7,3):
    print(j)

3
6


In [88]:
for j in range(7,5,-1):
    print(j)

7
6


In [ ]:
for j in range(10, -1, -1):
    print(j)

10
9
8
7
6
5
4
3
2
1


In [95]:
for j in range(-10, -5, 1):
    print(j)

-10
-9
-8
-7
-6


In [97]:
print(range(5))
print(list(range(5)))

range(0, 5)
[0, 1, 2, 3, 4]


In [98]:
a = (1, 2)
b = [1, 2]
print(type(a), type(b))

<class 'tuple'> <class 'list'>


In [ ]:
r = range(0, 100, 2)  # Even numbers from 0 to 98
sub_r = r[5:15]       # Slicing from index 5 to 14

print(sub_r)          # Output: range(10, 30, 2)
print(type(sub_r))    # Output: <class 'range'>

range(10, 30, 2)
<class 'range'>


In [101]:
try:
    # Code that might cause an error
    number = int(input("Enter a number: "))
    result = 10 / number
except ZeroDivisionError:
    # Runs if the user enters 0
    print("You can't divide by zero!")
except ValueError:
    # Runs if the user enters "abc"
    print("That's not a valid number!")

You can't divide by zero!


In [103]:
def func(x):
    x = x + 1
    return x

a = 5
func(a)
print(a)

5


In [104]:
def func(lst):
    lst.append(4)

a = [1,2,3]
func(a)
print(a)

[1, 2, 3, 4]


In [108]:
a = [1, 2, 3, 4]
print(a)
a = a + [5]
print(a)

[1, 2, 3, 4]
[1, 2, 3, 4, 5]


In [112]:
a = [1, 2, 3, 4]
print(a)
a = a + [5] #concatenation
print(a)
print(sum(a))

[1, 2, 3, 4]
[1, 2, 3, 4, 5]
15


In [113]:
f = lambda x,y : x**2 - 2*x*y + y**2
print(f(2,3))

1


In [120]:
def is_palindrome(word):
    word = word.lower()
    if len(word) <= 1:
        return True
    
    if word[0] != word[-1]:
        return False
    
    return is_palindrome(word[1:len(word)-1])

result1 = is_palindrome("Mom")
print(result1)

True


In [123]:
def sum_digits(n):
    if n < 10:
        return n
    return n%10 + sum_digits(n//10)

result = sum_digits(567342)
print(result)

27


In [127]:
def power(base, exp):
    if exp == 0:
        return 1
    
    if exp < 0:
        return 1 / power(base, -exp)
    
    return base * power(base, exp-1)

y = power(2,-1)
print(y)

0.5


In [129]:
x = 0

for i in range(3):
    for j in range(3):
        if i == j:
            continue
        x += 1

print(x)

6


In [130]:
lst = [1, 2, 3]

for i in range(len(lst)):
    lst.append(i)

print(lst)

[1, 2, 3, 0, 1, 2]


In [132]:
x = 1

for i in range(1, 4):
    x *= i

    if x % 2 == 0:
        x += 1

print(x)

9


In [134]:
lst = [1, 2, 3, 4]

for x in lst:
    if x % 2 == 0:
        lst.remove(x)

print(lst)

[1, 3]


In [135]:
s = "abcdef"
print(s[-1:-5:-2])

fd


In [136]:
x = 0

for i in range(3):
    for j in range(i, 3):
        x += 1

print(x)

6


In [137]:
lst = [1, 2, 3]

for i in lst:
    lst.append(i)

    if len(lst) > 5:
        break

print(lst)

[1, 2, 3, 1, 2, 3]


In [138]:
x = 0

for i in range(5):
    if i % 2 == 0:
        continue
    x += i

print(x)

4


In [139]:
def func(x):
    x = x + [4]
    return x

a = [1, 2, 3]
func(a)

print(a)

[1, 2, 3]


In [141]:
s = "abcd"
lst = list(s)

lst[1:3] = ["x", "y", "z"]

print(lst)

['a', 'x', 'y', 'z', 'd']


In [142]:
a = [1, 2, 3]

def func(x):
    x.append(4)

func(a)
print(a)

[1, 2, 3, 4]


In [143]:
a = [1, 2, 3]

def func(x):
    x = x * 2

func(a)
print(a)

[1, 2, 3]


In [144]:
a = [1, 2]

def func(x):
    x.append(3)

func(a)
print(a)

[1, 2, 3]


In [145]:
a = [1, 2]

def func(x):
    x = x + [3]

func(a)
print(a)

[1, 2]


In [146]:
a = [1, 2]

def func(x):
    x = x
    x.append(3)

func(a)
print(a)

[1, 2, 3]


In [147]:
a = [1, 2]

def func(x):
    x = x[:]
    x.append(3)

func(a)
print(a)

[1, 2]


In [149]:
s = "Kirti"
print(id(s))
s = s.lower()
print(id(s))
print(s)

135887779665072
135887606153264
kirti


In [161]:
s = "K i r t i"
s1 = s.split(" ")
print(s1)

['K', 'i', 'r', 't', 'i']


In [159]:
print(ord('a'))

97


In [162]:
lst = [1,2,3]
x = lst.pop()
print(lst, x)

[1, 2] 3


In [163]:
lst = [3,1,2]
print(lst.sort())

None


In [164]:
lst = [(2,3),(1,5),(2,1)]
lst.sort(key=lambda x: x[0])
print(lst)

[(1, 5), (2, 3), (2, 1)]


In [170]:
s = "plutonium"
print(len(s))
print(s[0])
print(s[8])
# print(s[9])
print(s[-9])
print(s[-1:-10:-1])
print(s[::-1])
print(s[::1])
print(s[2::4])
print(s[2:4:2])
print(s[2:4])

9
p
m
p
muinotulp
muinotulp
plutonium
ui
u
ut


In [173]:
s = "kirti"
s = s.replace('i', 'I')
print(s)

kIrtI


In [174]:
s = "k i r t i"
help(str.split)

Help on method_descriptor:

split(self, /, sep=None, maxsplit=-1)
    Return a list of the substrings in the string, using sep as the separator string.
    
      sep
        The separator used to split the string.
    
        When set to None (the default value), will split on any whitespace
        character (including \\n \\r \\t \\f and spaces) and will discard
        empty strings from the result.
      maxsplit
        Maximum number of splits (starting from the left).
        -1 (the default value) means no limit.
    
    Note, str.split() is mainly useful for data that has been intentionally
    delimited.  With natural text that includes punctuation, consider using
    the regular expression module.



In [181]:
print(s.split(sep = ' ', maxsplit=3))

['k', 'i', 'r', 't i']


In [ ]:
s = "abcdef"
print(s[-2:1:-2])

ec


In [183]:
x = 0

for i in range(4):
    for j in range(i):
        if j % 2 == 0:
            x += j

print(x)

2


In [184]:
def func(x):
    x.append(1)
    x = x + [2]
    return x

a = [0]
func(a)

print(a)

[0, 1]


In [187]:
def is_prime(n, divisor=2):
    if n < 2:
        return False
    
    if n == 2:
        return True
    
    if divisor > math.sqrt(n):
        return True
    
    if n%divisor == 0:
        return False
    
    return is_prime(n, divisor+1)

print(is_prime(27))

False


In [198]:
n = int(input())
if type(n) is not int:
    print("enter an actual non negetive number")
else:
    count = 0
    for i in range(2, n):
        if n%i == 0:
            count += 1
    if count > 0:
        print(f"{n} is not a prime")
    else:
        print(f"{n} is a prime")

19 is a prime


In [191]:
a, m = [], []
for i in range(5):
    for j in range(5):
        a.append(0)
    m.append(a)
    a = []
print(m)

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [ ]:
s = 0
c = 1
while True:
    n = input("enter numbers to calculate average, q to quit")
    if n == 'q':
        print("\nEnding...")
        break
    else:
        print(n, end=' ')
        n = int(n)
        s += n
        c += 1
        avg = s/(c-1)
print (f"\nFinal sum is {s}")
print (f"Final Avg is {avg}")

63 25 47 98 99 99 60 47 00 63 24 58 Ending...

Final sum is 683
Final Avg is 56.916666666666664


In [196]:
def f(x):
    return 2*x
a = 0
b = 1
n = 100
h = (b-a)/100
s = 0
for i in range(1, n):
    s += f(a + i*h)
integral = (h/2)*(f(a) + 2*s + f(b))
print(integral)

1.0


In [197]:
print(list(range(5,5)))

[]


In [204]:
n = int(input("Enter limit upto which you want prime"))
for i in range(1, n+1):
    m = i
    if m == 2 or m == 3:
        print(f"{m} is a prime", end = " ")
    elif m<2 or m%2 == 0 or m%3 == 0:
        continue
    else:
        c = 0
        for j in range(4, m):
            if m%j == 0:
                c += 1
        if c>0:
            continue
        else:
            print(f"{m} is a prime",  end = " ")

2 is a prime 3 is a prime 5 is a prime 7 is a prime 

In [8]:
s, c = 0, 0
while True:
    n = input("enter numbers to perform avg, q to quit")
    try:
        if n != 'q':
            n = int(n)
            s += n
            c += 1
            avg = s/c
    except ZeroDivisionError:
        print("No inputs received, please enter a number")
    else:
        print(f"Final average after {n} is {avg:.4f}")
    finally:
        if n == 'q':
            print("Quitting...")
            break


Final average after 100 is 100.0000
Final average after 63 is 81.5000
Final average after 47 is 70.0000
Final average after 58 is 67.0000
Final average after 65 is 66.6000
Final average after 33 is 61.0000
Final average after 47 is 59.0000
Final average after 97 is 63.7500
Final average after 54 is 62.6667
Final average after 26 is 59.0000
Final average after 29 is 56.2727
Final average after 65 is 57.0000
Final average after q is 57.0000
Quitting...


In [5]:
m = []
for i in range(3):
    a = []
    for j in range(3):
        a.append(i*j)
    m.append(a)
for i in range(3):
    for j in range(3):
        print(m[i][j], end=" ")
    print()

0 0 0 
0 1 2 
0 2 4 


In [11]:
def f(x):
    return 2*x
a = int(input("enter lower limit of integral"))
b = int(input("enter upper limit of integral"))
n = int(input("enter number of steps"))
h = (b-a)/n if n>0 else print("Invalid n, n must be greater than 0")
s = 0
for i in range(1, n):
    s += f(a + i*h)
integral = (h/2)*(f(a) + 2*s + f(b))
print(f"final integral is {integral:.4f}")

final integral is 4.0000


In [16]:
s = input("enter a string")
s = s.lower().strip()
final = []
for i in range(97, 123):
    final.append([chr(i), 0])
for char in s:
    index = ord(char)
    if 97 <= index <= 122:
        final[index-97][1] += 1
for x,y in final:
    if y>0:
        print(f"{x}:{y}")

a:1
b:1
c:1
d:1
e:1
f:1


In [18]:
lst = [1,2,3,4,5,6]

for i in range(len(lst)):
    if lst[i] % 2 == 0:
        lst.pop(i)

print(lst)

IndexError: list index out of range

In [19]:
def func(x):
    x.append(10)
    x = x + [20]
    x.append(30)
    return x

a = [1,2]
b = func(a)

print(a)
print(b)

[1, 2, 10]
[1, 2, 10, 20, 30]


In [23]:
lst = [(2,3),(1,5),(2,1),(1,2)]

lst.sort(key=lambda x: (x[0], -x[1]))

print(lst)

[(1, 5), (1, 2), (2, 3), (2, 1)]


In [ ]:
num_list = [1,2,4,5,6,8,7,8,9,0,4,5,5,6,4,3,2,6,7,8,0,1,2,6,3,4,7]
temp = set(num_list)
print(temp)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [35]:
num_list = [1,2,4,5,6,8,7,8,9,0,4,5,5,6,4,3,2,6,7,8,0,1,2,6,3,4,7]
seen = set()
temp = []
for i in num_list:
    if i not in seen:
        temp.append(i)
        seen.add(i)
temp.sort(key = lambda x : x%2==0)     
print(temp)  

[1, 5, 7, 9, 3, 2, 4, 6, 8, 0]
